import { AuthProvider } from "@/lib/context/AuthContext";
import { CartProvider } from "@/lib/context/CartContext";
import Footer from "@/components/layouts/footer/Footer";
import "@/styles/globals.css";

export const metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
};

export default function AppLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased flex flex-col min-h-screen scroll-smooth">
        <AuthProvider>
          <CartProvider>
            <main className="main ">{children}</main>
          </CartProvider>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
