import { AuthProvider } from "@/lib/context/AuthContext";
import { CartProvider } from "@/lib/context/CartContext";
import Header from "@/components/layouts/header/Header";
import Footer from "@/components/layouts/footer/Footer";
import "@/styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AppLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased flex flex-col min-h-screen">
        <AuthProvider>
          <CartProvider>
            <main className="main ">{children}</main>
          </CartProvider>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
// import Header from "@/components/layouts/header/Header";
// import Footer from "@/components/layouts/footer/Footer";

// export default async function HomeLayout({ children }) {
//   return (
//     <div className="flex flex-col min-h-screen scroll-smooth">
//       <Header />
//       <main className="flex-1 flex flex-col">{children}</main>
//       <Footer />
//     </div>
//   );
// }
