import { AuthProvider } from "@/lib/context/AuthContext";
import { CartProvider } from "@/lib/context/CartContext";
import Footer from "@/components/layouts/footer/Footer";
import "@/styles/globals.css";
import { Analytics } from "@vercel/analytics/next";

export const metadata = {
  title: "E-commerce App",
  description: "Generated by create next app",
};

export default function AppLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased flex flex-col min-h-screen scroll-smooth">
        <AuthProvider>
          <CartProvider>
            <div className="fixed bottom-2 right-2 text-xs font-mono bg-black text-white px-2 py-1 rounded z-50 pointer-events-none">
              <div className="block sm:hidden">xs</div>
              <div className="hidden sm:block md:hidden">sm</div>
              <div className="hidden md:block lg:hidden">md</div>
              <div className="hidden lg:block xl:hidden">lg</div>
              <div className="hidden xl:block 2xl:hidden">xl</div>
              <div className="hidden 2xl:block">2xl</div>
            </div>
            <main className="main ">{children}</main>
          </CartProvider>
          <Footer />
        </AuthProvider>
        <Analytics />
      </body>
    </html>
  );
}
