import slugify from "./src/utils/formatters.js";
const data = [
  {
    name: "American Football",
    slug: "american-football",
    category: "sports-accessories",
    image:
      "https://cdn.dummyjson.com/product-images/sports-accessories/american-football/1.webp",
    price: 19.99,
    description:
      "The American Football is a classic ball used in American football games. It is designed for throwing and catching, making it an essential piece of equipment for the sport.",
    countInStock: 53,
    tags: ["sports equipment", "american football"],
    sizes: [],
    colors: [],
    isPublished: true,
    avgRating: 4.91,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 0,
      2: 0,
      3: 0,
      4: 3,
      5: 0,
    },
    reviews: [],
  },
  {
    name: "Baseball Ball",
    slug: "baseball-ball",
    category: "sports-accessories",
    image:
      "https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/1.webp",
    price: 8.99,
    description:
      "The Baseball Ball is a standard baseball used in baseball games. It features a durable leather cover and is designed for pitching, hitting, and fielding in the game of baseball.",
    countInStock: 100,
    tags: ["sports equipment", "baseball"],
    sizes: [],
    colors: [],
    isPublished: true,
    avgRating: 2.57,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 1,
      2: 0,
      3: 0,
      4: 1,
      5: 1,
    },
    reviews: [],
  },
  {
    name: "Baseball Glove",
    slug: "baseball-glove",
    category: "sports-accessories",
    image:
      "https://cdn.dummyjson.com/product-images/sports-accessories/baseball-glove/1.webp",
    price: 24.99,
    description:
      "The Baseball Glove is a protective glove worn by baseball players. It is designed to catch and field the baseball, providing players with comfort and control during the game.",
    countInStock: 22,
    tags: ["sports equipment", "baseball"],
    sizes: [],
    colors: [],
    isPublished: true,
    avgRating: 3.96,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 1,
      2: 0,
      3: 1,
      4: 1,
      5: 0,
    },
    reviews: [],
  },
  {
    name: "Basketball",
    slug: "basketball",
    category: "sports-accessories",
    image:
      "https://cdn.dummyjson.com/product-images/sports-accessories/basketball/1.webp",
    price: 14.99,
    description:
      "The Basketball is a standard ball used in basketball games. It is designed for dribbling, shooting, and passing in the game of basketball, suitable for both indoor and outdoor play.",
    countInStock: 75,
    tags: ["sports equipment", "basketball"],
    sizes: [],
    colors: [],
    isPublished: true,
    avgRating: 4.66,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 0,
      2: 1,
      3: 0,
      4: 1,
      5: 1,
    },
    reviews: [],
  },
  {
    name: "Basketball Rim",
    slug: "basketball-rim",
    category: "sports-accessories",
    image:
      "https://cdn.dummyjson.com/product-images/sports-accessories/basketball-rim/1.webp",
    price: 39.99,
    description:
      "The Basketball Rim is a sturdy hoop and net assembly mounted on a basketball backboard. It provides a target for shooting and scoring in the game of basketball.",
    countInStock: 43,
    tags: ["sports equipment", "basketball"],
    sizes: [],
    colors: [],
    isPublished: true,
    avgRating: 4.6,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 1,
      2: 0,
      3: 0,
      4: 1,
      5: 1,
    },
    reviews: [],
  },
  {
    name: "Cricket Ball",
    slug: "cricket-ball",
    category: "sports-accessories",
    image:
      "https://cdn.dummyjson.com/product-images/sports-accessories/cricket-ball/1.webp",
    price: 12.99,
    description:
      "The Cricket Ball is a hard leather ball used in the sport of cricket. It is bowled and batted in the game, and its hardness and seam contribute to the dynamics of cricket play.",
    countInStock: 30,
    tags: ["sports equipment", "cricket"],
    sizes: [],
    colors: [],
    isPublished: true,
    avgRating: 3.53,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 2,
      2: 1,
      3: 0,
      4: 0,
      5: 0,
    },
    reviews: [],
  },
  {
    name: "Black Women's Gown",
    slug: "black-womens-gown",
    category: "women-dresses",
    image:
      "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/thumbnail.webp",
    price: 129.99,
    description:
      "The Black Women's Gown is an elegant and timeless evening gown. With a sleek black design, it's perfect for formal events and special occasions, exuding sophistication and style.",
    countInStock: 25,
    tags: ["clothing", "gowns"],
    sizes: [],
    colors: [],
    isPublished: false,
    avgRating: 4,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 0,
      2: 0,
      3: 1,
      4: 1,
      5: 1,
    },
    reviews: [],
  },
  {
    name: "Corset Leather With Skirt",
    slug: "corset-leather-with-skirt",
    category: "women-dresses",
    image:
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/thumbnail.webp",
    price: 89.99,
    description:
      "The Corset Leather With Skirt is a bold and edgy ensemble that combines a stylish corset with a matching skirt. Ideal for fashion-forward individuals, it makes a statement at any event.",
    countInStock: 30,
    tags: ["clothing", "corsets", "skirts"],
    sizes: [],
    colors: [],
    isPublished: false,
    avgRating: 4.33,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 0,
      2: 0,
      3: 0,
      4: 2,
      5: 1,
    },
    reviews: [],
  },
  {
    name: "Corset With Black Skirt",
    slug: "corset-with-black-skirt",
    category: "women-dresses",
    image:
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/thumbnail.webp",
    price: 79.99,
    description:
      "The Corset With Black Skirt is a chic and versatile outfit that pairs a fashionable corset with a classic black skirt. It offers a trendy and coordinated look for various occasions.",
    countInStock: 33,
    tags: ["clothing", "corsets", "skirts"],
    sizes: [],
    colors: [],
    isPublished: false,
    avgRating: 4,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 0,
      2: 1,
      3: 0,
      4: 0,
      5: 2,
    },
    reviews: [],
  },
  {
    name: "Dress Pea",
    slug: "dress-pea",
    category: "women-dresses",
    image:
      "https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/thumbnail.webp",
    price: 49.99,
    description:
      "The Dress Pea is a stylish and comfortable dress with a pea pattern. Perfect for casual outings, it adds a playful and fun element to your wardrobe, making it a great choice for day-to-day wear.",
    countInStock: 6,
    tags: ["clothing", "dresses"],
    sizes: [],
    colors: [],
    isPublished: false,
    avgRating: 2.33,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 1,
      2: 1,
      3: 0,
      4: 1,
      5: 0,
    },
    reviews: [],
  },
  {
    name: "Marni Red & Black Suit",
    slug: "marni-red-black-suit",
    category: "women-dresses",
    image:
      "https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/thumbnail.webp",
    price: 179.99,
    description:
      "The Marni Red & Black Suit is a sophisticated and fashion-forward suit ensemble. With a combination of red and black tones, it showcases a modern design for a bold and confident look.",
    countInStock: 62,
    tags: ["clothing", "suits"],
    sizes: [],
    colors: [],
    isPublished: false,
    avgRating: 4,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 0,
      2: 0,
      3: 1,
      4: 1,
      5: 1,
    },
    reviews: [],
  },
  {
    name: "Blue & Black Check Shirt",
    slug: "blue-black-check-shirt",
    category: "mens-shirts",
    image:
      "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/1.webp",
    price: 29.99,
    description:
      "The Blue & Black Check Shirt is a stylish and comfortable men's shirt featuring a classic check pattern. Made from high-quality fabric, it's suitable for both casual and semi-formal occasions.",
    countInStock: 38,
    tags: ["clothing", "men's shirts"],
    sizes: [],
    colors: [],
    isPublished: false,
    avgRating: 3.64,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 1,
      2: 0,
      3: 0,
      4: 1,
      5: 1,
    },
    reviews: [],
  },
  {
    name: "Gigabyte Aorus Men Tshirt",
    slug: "gigabyte-aorus-men-tshirt",
    category: "mens-shirts",
    image:
      "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/1.webp",
    price: 24.99,
    description:
      "The Gigabyte Aorus Men Tshirt is a cool and casual shirt for gaming enthusiasts. With the Aorus logo and sleek design, it's perfect for expressing your gaming style.",
    countInStock: 90,
    tags: ["clothing", "men's t-shirts"],
    sizes: [],
    colors: [],
    isPublished: false,
    avgRating: 3.18,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 1,
      2: 0,
      3: 0,
      4: 0,
      5: 2,
    },
    reviews: [],
  },
  {
    name: "Man Plaid Shirt",
    slug: "man-plaid-shirt",
    category: "mens-shirts",
    image:
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/1.webp",
    price: 34.99,
    description:
      "The Man Plaid Shirt is a timeless and versatile men's shirt with a classic plaid pattern. Its comfortable fit and casual style make it a wardrobe essential for various occasions.",
    countInStock: 82,
    tags: ["clothing", "men's shirts"],
    sizes: [],
    colors: [],
    isPublished: false,
    avgRating: 3.46,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 0,
      2: 1,
      3: 1,
      4: 1,
      5: 0,
    },
    reviews: [],
  },
  {
    name: "Man Short Sleeve Shirt",
    slug: "man-short-sleeve-shirt",
    category: "mens-shirts",
    image:
      "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/1.webp",
    price: 19.99,
    description:
      "The Man Short Sleeve Shirt is a breezy and stylish option for warm days. With a comfortable fit and short sleeves, it's perfect for a laid-back yet polished look.",
    countInStock: 2,
    tags: ["clothing", "men's shirts"],
    sizes: [],
    colors: [],
    isPublished: false,
    avgRating: 2.9,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 1,
      2: 1,
      3: 0,
      4: 0,
      5: 1,
    },
    reviews: [],
  },
  {
    name: "Men Check Shirt",
    slug: "men-check-shirt",
    category: "mens-shirts",
    image:
      "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/1.webp",
    price: 27.99,
    description:
      "The Men Check Shirt is a classic and versatile shirt featuring a stylish check pattern. Suitable for various occasions, it adds a smart and polished touch to your wardrobe.",
    countInStock: 95,
    tags: ["clothing", "men's shirts"],
    sizes: [],
    colors: [],
    isPublished: false,
    avgRating: 2.72,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 0,
      2: 1,
      3: 1,
      4: 0,
      5: 1,
    },
    reviews: [],
  },
  {
    name: "iPhone 13 Pro",
    slug: "iphone-13-pro",
    category: "smartphones",
    image:
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp",
    price: 1099.99,
    description:
      "The iPhone 13 Pro is the latest Apple flagship smartphone featuring advanced camera technology, A15 Bionic chip, and a stunning OLED display.",
    countInStock: 56,
    tags: ["smartphones", "apple"],
    sizes: [],
    colors: [],
    isPublished: true,
    avgRating: 4.12,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 0,
      2: 0,
      3: 1,
      4: 0,
      5: 2,
    },
    reviews: [],
  },
  {
    name: "iPhone X",
    slug: "iphone-x",
    category: "smartphones",
    image:
      "https://cdn.dummyjson.com/product-images/smartphones/iphone-x/thumbnail.webp",
    price: 899.99,
    description:
      "The iPhone X is a flagship smartphone featuring a bezel-less OLED display, facial recognition technology (Face ID), and impressive performance. It represents a milestone in iPhone design and innovation.",
    countInStock: 37,
    tags: ["smartphones", "apple"],
    sizes: [],
    colors: [],
    isPublished: true,
    avgRating: 2.51,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 0,
      2: 1,
      3: 0,
      4: 1,
      5: 1,
    },
    reviews: [],
  },
  {
    name: "Oppo A57",
    slug: "oppo-a57",
    category: "smartphones",
    image:
      "https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/thumbnail.webp",
    price: 249.99,
    description:
      "The Oppo A57 is a mid-range smartphone known for its sleek design and capable features. It offers a balance of performance and affordability, making it a popular choice.",
    countInStock: 19,
    tags: ["smartphones", "oppo"],
    sizes: [],
    colors: [],
    isPublished: true,
    avgRating: 3.94,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 0,
      2: 1,
      3: 0,
      4: 2,
      5: 0,
    },
    reviews: [],
  },
  {
    name: "Oppo F19 Pro Plus",
    slug: "oppo-f19-pro-plus",
    category: "smartphones",
    image:
      "https://cdn.dummyjson.com/product-images/smartphones/oppo-f19-pro-plus/thumbnail.webp",
    price: 399.99,
    description:
      "The Oppo F19 Pro Plus is a feature-rich smartphone with a focus on camera capabilities. It boasts advanced photography features and a powerful performance for a premium user experience.",
    countInStock: 78,
    tags: ["smartphones", "oppo"],
    sizes: [],
    colors: [],
    isPublished: true,
    avgRating: 3.51,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 0,
      2: 0,
      3: 0,
      4: 1,
      5: 2,
    },
    reviews: [],
  },
  {
    name: "American Football",
    slug: "american-football",
    category: "sports-accessories",
    image:
      "https://cdn.dummyjson.com/product-images/sports-accessories/american-football/1.webp",
    price: 19.99,
    description:
      "The American Football is a classic ball used in American football games. It is designed for throwing and catching, making it an essential piece of equipment for the sport.",
    countInStock: 53,
    tags: ["sports equipment", "american football"],
    sizes: [],
    colors: [],
    isPublished: false,
    avgRating: 4,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 0,
      2: 0,
      3: 0,
      4: 3,
      5: 0,
    },
    reviews: [],
  },
  {
    name: "Baseball Ball",
    slug: "baseball-ball",
    category: "sports-accessories",
    image:
      "https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/1.webp",
    price: 8.99,
    description:
      "The Baseball Ball is a standard baseball used in baseball games. It features a durable leather cover and is designed for pitching, hitting, and fielding in the game of baseball.",
    countInStock: 100,
    tags: ["sports equipment", "baseball"],
    sizes: [],
    colors: [],
    isPublished: false,
    avgRating: 3.33,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 1,
      2: 0,
      3: 0,
      4: 1,
      5: 1,
    },
    reviews: [],
  },
  {
    name: "Baseball Glove",
    slug: "baseball-glove",
    category: "sports-accessories",
    image:
      "https://cdn.dummyjson.com/product-images/sports-accessories/baseball-glove/1.webp",
    price: 24.99,
    description:
      "The Baseball Glove is a protective glove worn by baseball players. It is designed to catch and field the baseball, providing players with comfort and control during the game.",
    countInStock: 22,
    tags: ["sports equipment", "baseball"],
    sizes: [],
    colors: [],
    isPublished: false,
    avgRating: 2.67,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 1,
      2: 0,
      3: 1,
      4: 1,
      5: 0,
    },
    reviews: [],
  },
  {
    name: "Basketball",
    slug: "basketball",
    category: "sports-accessories",
    image:
      "https://cdn.dummyjson.com/product-images/sports-accessories/basketball/1.webp",
    price: 14.99,
    description:
      "The Basketball is a standard ball used in basketball games. It is designed for dribbling, shooting, and passing in the game of basketball, suitable for both indoor and outdoor play.",
    countInStock: 75,
    tags: ["sports equipment", "basketball"],
    sizes: [],
    colors: [],
    isPublished: false,
    avgRating: 3.67,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 0,
      2: 1,
      3: 0,
      4: 1,
      5: 1,
    },

    reviews: [],
  },
  {
    name: "Green Crystal Earring",
    slug: "green-crystal-earring",
    category: "women-jewellery",
    image:
      "https://cdn.dummyjson.com/product-images/womens-jewellery/green-crystal-earring/thumbnail.webp",
    price: 29.99,
    description:
      "The Green Crystal Earring is a dazzling accessory that features a vibrant green crystal. With a classic design, it adds a touch of elegance to your ensemble, perfect for formal or special occasions.",
    countInStock: 54,
    tags: ["fashion accessories", "earrings"],
    sizes: [],
    colors: [],
    isPublished: true,
    avgRating: 3.96,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 0,
      2: 0,
      3: 0,
      4: 2,
      5: 1,
    },
    reviews: [],
  },
  {
    name: "Green Oval Earring",
    slug: "green-oval-earring",
    category: "women-jewellery",
    image:
      "https://cdn.dummyjson.com/product-images/womens-jewellery/green-oval-earring/thumbnail.webp",
    price: 24.99,
    description:
      "The Green Oval Earring is a stylish and versatile accessory with a unique oval shape. Whether for casual or dressy occasions, its green hue and contemporary design make it a standout piece.",
    countInStock: 73,
    tags: ["fashion accessories", "earrings"],
    sizes: [],
    colors: [],
    isPublished: true,
    avgRating: 3.57,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 0,
      2: 0,
      3: 1,
      4: 1,
      5: 1,
    },
    reviews: [],
  },
  {
    name: "Tropical Earring",
    slug: "tropical-earring",
    category: "women-jewellery",
    image:
      "https://cdn.dummyjson.com/product-images/womens-jewellery/tropical-earring/thumbnail.webp",
    price: 19.99,
    description:
      "The Tropical Earring is a fun and playful accessory inspired by tropical elements. Featuring vibrant colors and a lively design, it's perfect for adding a touch of summer to your look.",
    countInStock: 1,
    tags: ["fashion accessories", "earrings"],
    sizes: [],
    colors: [],
    isPublished: true,
    avgRating: 4.4,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 1,
      2: 0,
      3: 0,
      4: 1,
      5: 1,
    },
    reviews: [],
  },
  {
    name: "Annibale Colombo Bed",
    slug: "annibale-colombo-bed",
    category: "furniture",
    image:
      "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp",
    price: 1899.99,
    description:
      "The Annibale Colombo Bed is a luxurious and elegant bed frame, crafted with high-quality materials for a comfortable and stylish bedroom.",
    countInStock: 88,
    tags: ["furniture", "beds"],
    sizes: [],
    colors: [],
    isPublished: false,
    avgRating: 2.33,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 1,
      2: 1,
      3: 0,
      4: 1,
      5: 0,
    },
    reviews: [],
  },
  {
    name: "Annibale Colombo Sofa",
    slug: "annibale-colombo-sofa",
    category: "furniture",
    image:
      "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp",
    price: 2499.99,
    description:
      "The Annibale Colombo Sofa is a sophisticated and comfortable seating option, featuring exquisite design and premium upholstery for your living room.",
    countInStock: 60,
    tags: ["furniture", "sofas"],
    sizes: [],
    colors: [],
    isPublished: false,
    avgRating: 3.0,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 1,
      2: 0,
      3: 1,
      4: 0,
      5: 1,
    },
    reviews: [],
  },
  {
    name: "Bedside Table African Cherry",
    slug: "bedside-table-african-cherry",
    category: "furniture",
    image:
      "https://cdn.dummyjson.com/product-images/furniture/bedside-table-african-cherry/thumbnail.webp",
    price: 299.99,
    description:
      "The Bedside Table in African Cherry is a stylish and functional addition to your bedroom, providing convenient storage space and a touch of elegance.",
    countInStock: 64,
    tags: ["furniture", "bedside tables"],
    sizes: [],
    colors: [],
    isPublished: false,
    avgRating: 4.0,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 0,
      2: 0,
      3: 0,
      4: 3,
      5: 0,
    },
    reviews: [],
  },
  {
    name: "Knoll Saarinen Executive Conference Chair",
    slug: "knoll-saarinen-executive-conference-chair",
    category: "furniture",
    image:
      "https://cdn.dummyjson.com/product-images/furniture/knoll-saarinen-executive-conference-chair/thumbnail.webp",
    price: 499.99,
    description:
      "The Knoll Saarinen Executive Conference Chair is a modern and ergonomic chair, perfect for your office or conference room with its timeless design.",
    countInStock: 26,
    tags: ["furniture", "office chairs"],
    sizes: [],
    colors: [],
    isPublished: false,
    avgRating: 3.0,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 0,
      2: 2,
      3: 0,
      4: 0,
      5: 1,
    },
    reviews: [],
  },
  {
    name: "Wooden Bathroom Sink With Mirror",
    slug: "wooden-bathroom-sink-with-mirror",
    category: "furniture",
    image:
      "https://cdn.dummyjson.com/product-images/furniture/wooden-bathroom-sink-with-mirror/thumbnail.webp",
    price: 799.99,
    description:
      "The Wooden Bathroom Sink with Mirror is a unique and stylish addition to your bathroom, featuring a wooden sink countertop and a matching mirror.",
    countInStock: 7,
    tags: ["furniture", "bathroom"],
    sizes: [],
    colors: [],
    isPublished: false,
    avgRating: 4.0,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 0,
      2: 0,
      3: 1,
      4: 1,
      5: 1,
    },
    reviews: [],
  },
  {
    name: "Brown Leather Belt Watch",
    slug: "brown-leather-belt-watch",
    category: "mens-watches",
    image:
      "https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/thumbnail.webp",
    price: 89.99,
    description:
      "The Brown Leather Belt Watch is a stylish timepiece with a classic design. Featuring a genuine leather strap and a sleek dial, it adds a touch of sophistication to your look.",
    countInStock: 32,
    tags: ["watches", "leather watches"],
    sizes: [],
    colors: [],
    isPublished: false,
    avgRating: 4.19,
    numReviews: 3,
    numSales: 0,
    rateDistribution: {
      1: 1,
      2: 0,
      3: 0,
      4: 2,
      5: 0,
    },
    reviews: [],
  },
];

export const products = data.map((product) => {
  // Update category mappings
  const categoryMapping = {
    Jewelry: "women-jewellery",
    "Women's Clothes": "women-dresses",
    "Men's Clothes": "men-shirts",
    Watches: "men-watches",
    "Sports & Outdoors": "sports-accessories",
    Smartphones: "smartphones",
    Furniture: "furniture",
  };

  const isClothing = ["women-dresses", "men-shirts"].includes(product.category);
  const isSmartphone = product.category === "smartphones";

  return {
    ...product,
    slug: slugify(product.name),
    category: categoryMapping[product.category] || product.category,
    sizes: isClothing ? ["S", "M", "L", "XL"] : [],
    colors: isSmartphone ? ["Blue", "Black", "White"] : [],
  };
});
// console.log(products.length);
